export const FETCH_API_REQUEST = 'FETCH_API_REQUEST'
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS'
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE'
export const SEARCH_FILTER = 'SEARCH_FILTER'

//THIS IS FOR FETCH MONTHLY COUNTRY CASES
export const FETCH_COUNTRY_API = 'FETCH_COUNTRY_API'
